services:
  server:
    build:
      context: .
      target: final
    network_mode: host
    ports:
      - 8000:8000
    environment:
      - PG_DBNAME=smartcab
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=test123
      - ADDRESS=0.0.0.0:8000
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=smartcab
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    network_mode: host
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: .secrets/db-password.txt
